import { MigrationInterface, QueryRunner } from "typeorm";

export class AddReportingAndSecurityEntities1760520722878 implements MigrationInterface {
    name = 'AddReportingAndSecurityEntities1760520722878'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "security_log" DROP CONSTRAINT "FK_1de635e6dd079e75eb11db8303c"`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" DROP CONSTRAINT "FK_10b8c1b5a5312ff18748f12bb2a"`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" DROP CONSTRAINT "FK_1f1efdcae59ea4b800cef779683"`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP CONSTRAINT "FK_28b94f42bd2fc619e33d397c059"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP CONSTRAINT "FK_1322e1ea1a925f933c0dd29de91"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP CONSTRAINT "FK_cce538277486b0782d385414b92"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP CONSTRAINT "FK_0ecd8c8f8baedd7289628818744"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP CONSTRAINT "FK_2fb547bb43affa1dca2bcd4d339"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP CONSTRAINT "FK_673d6ee83e9f5bc6d60f9df909a"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" DROP CONSTRAINT "FK_f5383a793f34f331400df11f2f8"`);
        await queryRunner.query(`ALTER TABLE "security_log" DROP COLUMN "action"`);
        await queryRunner.query(`DROP TYPE "public"."security_log_action_enum"`);
        await queryRunner.query(`ALTER TABLE "security_log" DROP COLUMN "success"`);
        await queryRunner.query(`ALTER TABLE "security_log" DROP COLUMN "resource"`);
        await queryRunner.query(`ALTER TABLE "security_log" DROP COLUMN "resourceId"`);
        await queryRunner.query(`ALTER TABLE "security_log" DROP COLUMN "ipAddress"`);
        await queryRunner.query(`ALTER TABLE "security_log" DROP COLUMN "userAgent"`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" DROP COLUMN "interviewId"`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" DROP COLUMN "maxParticipants"`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" DROP CONSTRAINT "UQ_f02412c2f98aa1927bbf1a6c0cd"`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" DROP COLUMN "roomId"`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" DROP COLUMN "participants"`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" DROP COLUMN "createdById"`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "report_metrics" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "report_metrics" DROP COLUMN "metricUnit"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "templateId"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "scheduleType"`);
        await queryRunner.query(`DROP TYPE "public"."report_schedule_scheduletype_enum"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "scheduleConfig"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "lastRunAt"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "nextRunAt"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP COLUMN "permissions"`);
        await queryRunner.query(`DROP TYPE "public"."report_share_permissions_enum"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP COLUMN "sharedWithId"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP COLUMN "sharedById"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN "isRead"`);
        await queryRunner.query(`ALTER TABLE "security_log" ADD "type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "security_log" ADD "ipHash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "security_log" ADD "userAgentHash" character varying`);
        await queryRunner.query(`ALTER TABLE "security_log" ADD "severity" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" ADD "metadata" json`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" ADD "createdBy" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."report_template_category_enum" AS ENUM('RECRUITMENT_METRICS', 'CANDIDATE_PIPELINE', 'INTERVIEW_ANALYTICS', 'HIRING_FUNNEL', 'TIME_TO_HIRE', 'COST_PER_HIRE', 'SOURCE_EFFECTIVENESS', 'COMPANY_OVERVIEW', 'DEPARTMENT_ANALYTICS', 'EMPLOYEE_METRICS', 'SUBSCRIPTION_USAGE', 'JOB_PERFORMANCE', 'APPLICATION_TRENDS', 'JOB_ANALYTICS', 'MARKET_ANALYSIS', 'COMMUNICATION_METRICS', 'ENGAGEMENT_ANALYTICS', 'RESPONSE_RATES', 'USER_ACTIVITY', 'SYSTEM_PERFORMANCE', 'SECURITY_AUDIT', 'ERROR_ANALYTICS', 'BILLING_SUMMARY', 'REVENUE_ANALYTICS', 'COST_ANALYSIS', 'CUSTOM_ANALYTICS')`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD "category" "public"."report_template_category_enum" NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."report_template_format_enum" AS ENUM('PDF', 'EXCEL', 'CSV', 'JSON', 'HTML', 'DASHBOARD')`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD "format" "public"."report_template_format_enum" NOT NULL DEFAULT 'PDF'`);
        await queryRunner.query(`CREATE TYPE "public"."report_template_scope_enum" AS ENUM('GLOBAL', 'COMPANY', 'DEPARTMENT', 'USER')`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD "scope" "public"."report_template_scope_enum" NOT NULL DEFAULT 'COMPANY'`);
        await queryRunner.query(`CREATE TYPE "public"."report_template_datasource_enum" AS ENUM('APPLICATIONS', 'CANDIDATES', 'JOBS', 'INTERVIEWS', 'USERS', 'COMPANIES', 'COMMUNICATIONS', 'SECURITY_LOGS', 'CUSTOM_QUERY', 'MIXED')`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD "dataSource" "public"."report_template_datasource_enum" NOT NULL DEFAULT 'MIXED'`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD "queryTemplate" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD "defaultFilters" json`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD "defaultParameters" json`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD "isValidated" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD "validatedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD "validationError" text`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD "version" character varying(10) NOT NULL DEFAULT '1.0'`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD "isSystem" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD "usageCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD "lastUsed" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD "createdBy" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."report_metrics_metrictype_enum" AS ENUM('COUNT', 'SUM', 'AVERAGE', 'PERCENTAGE', 'TREND', 'COMPARISON', 'DISTRIBUTION', 'CUSTOM')`);
        await queryRunner.query(`ALTER TABLE "report_metrics" ADD "metricType" "public"."report_metrics_metrictype_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_metrics" ADD "dimension" character varying`);
        await queryRunner.query(`ALTER TABLE "report_metrics" ADD "metadata" json`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "reportId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD CONSTRAINT "UQ_675bc246be79896c578a1945fea" UNIQUE ("reportId")`);
        await queryRunner.query(`CREATE TYPE "public"."report_schedule_frequency_enum" AS ENUM('ONCE', 'DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', 'CUSTOM')`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "frequency" "public"."report_schedule_frequency_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "cronExpression" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "startDate" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "endDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "nextRun" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "lastRun" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "isPaused" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "timezone" character varying(50) NOT NULL DEFAULT 'UTC'`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "recipients" text array NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`CREATE TYPE "public"."report_schedule_deliveryformat_enum" AS ENUM('PDF', 'EXCEL', 'CSV', 'JSON', 'HTML', 'DASHBOARD')`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "deliveryFormat" "public"."report_schedule_deliveryformat_enum" NOT NULL DEFAULT 'PDF'`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "emailSubject" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "emailBody" text`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "includeAttachment" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "maxExecutionTime" integer`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "retryCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "maxRetries" integer NOT NULL DEFAULT '3'`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "consecutiveFailures" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "lastError" text`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "lastSuccessfulRun" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD "sharedWith" character varying(255)`);
        await queryRunner.query(`CREATE TYPE "public"."report_share_permission_enum" AS ENUM('VIEW_ONLY', 'EDIT', 'FULL_ACCESS')`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD "permission" "public"."report_share_permission_enum" NOT NULL DEFAULT 'VIEW_ONLY'`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD "accessToken" character varying(64)`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD CONSTRAINT "UQ_65a42b8d298382583c51c2b3958" UNIQUE ("accessToken")`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD "isRevoked" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD "revokedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD "accessCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD "maxAccessCount" integer`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD "lastAccessed" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD "ipRestrictions" text array NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD "isPublic" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD "requireLogin" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD "allowDownload" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD "watermark" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD "sharedBy" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD "shareNote" text`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ADD "success" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ADD "sessionId" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ADD "requestId" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ADD "duration" integer`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ADD "oldValues" json`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ADD "newValues" json`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ADD "riskLevel" character varying(10) NOT NULL DEFAULT 'LOW'`);
        await queryRunner.query(`CREATE TYPE "public"."report_category_enum" AS ENUM('RECRUITMENT_METRICS', 'CANDIDATE_PIPELINE', 'INTERVIEW_ANALYTICS', 'HIRING_FUNNEL', 'TIME_TO_HIRE', 'COST_PER_HIRE', 'SOURCE_EFFECTIVENESS', 'COMPANY_OVERVIEW', 'DEPARTMENT_ANALYTICS', 'EMPLOYEE_METRICS', 'SUBSCRIPTION_USAGE', 'JOB_PERFORMANCE', 'APPLICATION_TRENDS', 'JOB_ANALYTICS', 'MARKET_ANALYSIS', 'COMMUNICATION_METRICS', 'ENGAGEMENT_ANALYTICS', 'RESPONSE_RATES', 'USER_ACTIVITY', 'SYSTEM_PERFORMANCE', 'SECURITY_AUDIT', 'ERROR_ANALYTICS', 'BILLING_SUMMARY', 'REVENUE_ANALYTICS', 'COST_ANALYSIS', 'CUSTOM_ANALYTICS')`);
        await queryRunner.query(`ALTER TABLE "report" ADD "category" "public"."report_category_enum" NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."report_format_enum" AS ENUM('PDF', 'EXCEL', 'CSV', 'JSON', 'HTML', 'DASHBOARD')`);
        await queryRunner.query(`ALTER TABLE "report" ADD "format" "public"."report_format_enum" NOT NULL DEFAULT 'PDF'`);
        await queryRunner.query(`CREATE TYPE "public"."report_scope_enum" AS ENUM('GLOBAL', 'COMPANY', 'DEPARTMENT', 'USER')`);
        await queryRunner.query(`ALTER TABLE "report" ADD "scope" "public"."report_scope_enum" NOT NULL DEFAULT 'COMPANY'`);
        await queryRunner.query(`CREATE TYPE "public"."report_priority_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT')`);
        await queryRunner.query(`ALTER TABLE "report" ADD "priority" "public"."report_priority_enum" NOT NULL DEFAULT 'MEDIUM'`);
        await queryRunner.query(`ALTER TABLE "report" ADD "query" text`);
        await queryRunner.query(`CREATE TYPE "public"."report_datasource_enum" AS ENUM('APPLICATIONS', 'CANDIDATES', 'JOBS', 'INTERVIEWS', 'USERS', 'COMPANIES', 'COMMUNICATIONS', 'SECURITY_LOGS', 'CUSTOM_QUERY', 'MIXED')`);
        await queryRunner.query(`ALTER TABLE "report" ADD "dataSource" "public"."report_datasource_enum" NOT NULL DEFAULT 'MIXED'`);
        await queryRunner.query(`ALTER TABLE "report" ADD "filters" json`);
        await queryRunner.query(`ALTER TABLE "report" ADD "parameters" json`);
        await queryRunner.query(`CREATE TYPE "public"."report_executionstatus_enum" AS ENUM('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', 'TIMEOUT')`);
        await queryRunner.query(`ALTER TABLE "report" ADD "executionStatus" "public"."report_executionstatus_enum" NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "report" ADD "maxExecutionTime" integer`);
        await queryRunner.query(`ALTER TABLE "report" ADD "timeoutAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "report" ADD "fileUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "report" ADD "fileName" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "report" ADD "fileSize" integer`);
        await queryRunner.query(`ALTER TABLE "report" ADD "fileMimeType" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "report" ADD "templateId" character varying`);
        await queryRunner.query(`ALTER TABLE "report" ADD "generatedBy" character varying`);
        await queryRunner.query(`ALTER TABLE "report" ADD "executionTime" integer`);
        await queryRunner.query(`ALTER TABLE "report" ADD "recordCount" integer`);
        await queryRunner.query(`ALTER TABLE "report" ADD "autoDelete" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "report" ADD "isPublic" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "report" ADD "isArchived" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "report" ADD "archivedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "report" ADD "tags" text array NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "report" ADD "version" character varying(10) NOT NULL DEFAULT '1.0'`);
        await queryRunner.query(`ALTER TABLE "report" ADD "checksum" character varying(64)`);
        await queryRunner.query(`CREATE TYPE "public"."notification_category_enum" AS ENUM('APPLICATION', 'INTERVIEW', 'SYSTEM', 'CANDIDATE', 'OFFER')`);
        await queryRunner.query(`ALTER TABLE "notification" ADD "category" "public"."notification_category_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification" ADD "read" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "application" ADD "expectedSalary" character varying`);
        await queryRunner.query(`ALTER TABLE "application" ADD "noticePeriod" character varying`);
        await queryRunner.query(`ALTER TABLE "application" ADD "cvAnalysisScore" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "application" ADD "cvAnalysisResults" json`);
        await queryRunner.query(`ALTER TABLE "application" ADD "analyzedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "application" ADD "aiCvRecommendations" text`);
        await queryRunner.query(`ALTER TABLE "application" ADD "aiInterviewRecommendations" text`);
        await queryRunner.query(`ALTER TABLE "application" ADD "aiSecondInterviewRecommendations" text`);
        await queryRunner.query(`ALTER TABLE "application" ADD "recommendationsGeneratedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "application" ADD "companyNotes" text`);
        await queryRunner.query(`ALTER TABLE "application" ADD "reviewedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "application" ADD "interviewScheduledAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "application" ADD "interviewedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "application" ADD "rejectedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "application" ADD "acceptedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "security_log" DROP CONSTRAINT "PK_efed13f4d5863b4dd080994b486"`);
        await queryRunner.query(`ALTER TABLE "security_log" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "security_log" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "security_log" ADD CONSTRAINT "PK_efed13f4d5863b4dd080994b486" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "security_log" DROP COLUMN "details"`);
        await queryRunner.query(`ALTER TABLE "security_log" ADD "details" json NOT NULL`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" DROP CONSTRAINT "PK_5db8ccc7afe73509bf9bf3e6bf2"`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" ADD CONSTRAINT "PK_5db8ccc7afe73509bf9bf3e6bf2" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" ADD CONSTRAINT "UQ_dec6236278002920979985aba8b" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP CONSTRAINT "PK_d2952f5126d6e487e73ec6ae6a3"`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD CONSTRAINT "PK_d2952f5126d6e487e73ec6ae6a3" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."report_template_type_enum" RENAME TO "report_template_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."report_template_type_enum" AS ENUM('ANALYTICS', 'PERFORMANCE', 'COMPLIANCE', 'OPERATIONAL', 'FINANCIAL', 'SUMMARY', 'DETAILED', 'CUSTOM')`);
        await queryRunner.query(`ALTER TABLE "report_template" ALTER COLUMN "type" TYPE "public"."report_template_type_enum" USING "type"::"text"::"public"."report_template_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."report_template_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "report_template" ALTER COLUMN "config" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_metrics" DROP CONSTRAINT "FK_c44ef0cc4691706c776f3747818"`);
        await queryRunner.query(`ALTER TABLE "report_metrics" DROP CONSTRAINT "PK_8cfe3e42ad3515d6e0b25764f64"`);
        await queryRunner.query(`ALTER TABLE "report_metrics" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "report_metrics" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_metrics" ADD CONSTRAINT "PK_8cfe3e42ad3515d6e0b25764f64" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "report_metrics" DROP COLUMN "reportId"`);
        await queryRunner.query(`ALTER TABLE "report_metrics" ADD "reportId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP CONSTRAINT "PK_c7488f713986a70052eb10f1178"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD CONSTRAINT "PK_c7488f713986a70052eb10f1178" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP CONSTRAINT "FK_2f82afddd021b3b81482f10639d"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP CONSTRAINT "PK_818f8c1397a8942a9cccf32a3d4"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD CONSTRAINT "PK_818f8c1397a8942a9cccf32a3d4" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP COLUMN "reportId"`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD "reportId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" DROP CONSTRAINT "FK_72b16ce84a8b798badf608ff948"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" DROP CONSTRAINT "PK_e8cebe2d7eb2190ee1b5cacd21b"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ADD CONSTRAINT "PK_e8cebe2d7eb2190ee1b5cacd21b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" DROP COLUMN "reportId"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ADD "reportId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."report_audit_log_action_enum" RENAME TO "report_audit_log_action_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."report_audit_log_action_enum" AS ENUM('CREATED', 'UPDATED', 'DELETED', 'GENERATED', 'ACCESSED', 'SHARED', 'DOWNLOADED', 'SCHEDULED', 'UNSCHEDULED', 'ARCHIVED', 'RESTORED', 'PERMISSIONS_CHANGED', 'TEMPLATE_APPLIED', 'EXECUTION_STARTED', 'EXECUTION_COMPLETED', 'EXECUTION_FAILED', 'SHARE_REVOKED')`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ALTER COLUMN "action" TYPE "public"."report_audit_log_action_enum" USING "action"::"text"::"public"."report_audit_log_action_enum"`);
        await queryRunner.query(`DROP TYPE "public"."report_audit_log_action_enum_old"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" DROP COLUMN "details"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ADD "details" json`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ADD "userId" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" DROP COLUMN "ipAddress"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ADD "ipAddress" character varying(45)`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" DROP COLUMN "userAgent"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ADD "userAgent" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "report" DROP CONSTRAINT "FK_e347c56b008c2057c9887e230aa"`);
        await queryRunner.query(`ALTER TABLE "report" DROP CONSTRAINT "PK_99e4d0bea58cba73c57f935a546"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "report" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report" ADD CONSTRAINT "PK_99e4d0bea58cba73c57f935a546" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "report" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."report_type_enum" RENAME TO "report_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."report_type_enum" AS ENUM('ANALYTICS', 'PERFORMANCE', 'COMPLIANCE', 'OPERATIONAL', 'FINANCIAL', 'SUMMARY', 'DETAILED', 'CUSTOM')`);
        await queryRunner.query(`ALTER TABLE "report" ALTER COLUMN "type" TYPE "public"."report_type_enum" USING "type"::"text"::"public"."report_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."report_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."report_status_enum" RENAME TO "report_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."report_status_enum" AS ENUM('DRAFT', 'GENERATING', 'COMPLETED', 'FAILED', 'SCHEDULED', 'ARCHIVED')`);
        await queryRunner.query(`ALTER TABLE "report" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "report" ALTER COLUMN "status" TYPE "public"."report_status_enum" USING "status"::"text"::"public"."report_status_enum"`);
        await queryRunner.query(`ALTER TABLE "report" ALTER COLUMN "status" SET DEFAULT 'DRAFT'`);
        await queryRunner.query(`DROP TYPE "public"."report_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "report" ALTER COLUMN "config" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report" ALTER COLUMN "userId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."notification_type_enum" RENAME TO "notification_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."notification_type_enum" AS ENUM('SUCCESS', 'WARNING', 'INFO', 'ERROR')`);
        await queryRunner.query(`ALTER TABLE "notification" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "notification" ALTER COLUMN "type" TYPE "public"."notification_type_enum" USING "type"::"text"::"public"."notification_type_enum"`);
        await queryRunner.query(`ALTER TABLE "notification" ALTER COLUMN "type" SET DEFAULT 'INFO'`);
        await queryRunner.query(`DROP TYPE "public"."notification_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD CONSTRAINT "FK_991316425dea3190908f86d73d5" FOREIGN KEY ("createdBy") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_metrics" ADD CONSTRAINT "FK_c44ef0cc4691706c776f3747818" FOREIGN KEY ("reportId") REFERENCES "report"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD CONSTRAINT "FK_675bc246be79896c578a1945fea" FOREIGN KEY ("reportId") REFERENCES "report"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD CONSTRAINT "FK_2f82afddd021b3b81482f10639d" FOREIGN KEY ("reportId") REFERENCES "report"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD CONSTRAINT "FK_ee9888bdd3aa65d74501f5a6f3f" FOREIGN KEY ("sharedBy") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ADD CONSTRAINT "FK_72b16ce84a8b798badf608ff948" FOREIGN KEY ("reportId") REFERENCES "report"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report" ADD CONSTRAINT "FK_85c15b6b42bdfb71ed3c8d66c65" FOREIGN KEY ("templateId") REFERENCES "report_template"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report" ADD CONSTRAINT "FK_e347c56b008c2057c9887e230aa" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "report" DROP CONSTRAINT "FK_e347c56b008c2057c9887e230aa"`);
        await queryRunner.query(`ALTER TABLE "report" DROP CONSTRAINT "FK_85c15b6b42bdfb71ed3c8d66c65"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" DROP CONSTRAINT "FK_72b16ce84a8b798badf608ff948"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP CONSTRAINT "FK_ee9888bdd3aa65d74501f5a6f3f"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP CONSTRAINT "FK_2f82afddd021b3b81482f10639d"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP CONSTRAINT "FK_675bc246be79896c578a1945fea"`);
        await queryRunner.query(`ALTER TABLE "report_metrics" DROP CONSTRAINT "FK_c44ef0cc4691706c776f3747818"`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP CONSTRAINT "FK_991316425dea3190908f86d73d5"`);
        await queryRunner.query(`CREATE TYPE "public"."notification_type_enum_old" AS ENUM('JOB_APPLICATION', 'JOB_UPDATE', 'SYSTEM', 'MARKETING')`);
        await queryRunner.query(`ALTER TABLE "notification" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "notification" ALTER COLUMN "type" TYPE "public"."notification_type_enum_old" USING "type"::"text"::"public"."notification_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "notification" ALTER COLUMN "type" SET DEFAULT 'SYSTEM'`);
        await queryRunner.query(`DROP TYPE "public"."notification_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."notification_type_enum_old" RENAME TO "notification_type_enum"`);
        await queryRunner.query(`ALTER TABLE "report" ALTER COLUMN "userId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report" ALTER COLUMN "config" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."report_status_enum_old" AS ENUM('PENDING', 'GENERATING', 'COMPLETED', 'FAILED', 'EXPIRED')`);
        await queryRunner.query(`ALTER TABLE "report" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "report" ALTER COLUMN "status" TYPE "public"."report_status_enum_old" USING "status"::"text"::"public"."report_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "report" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."report_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."report_status_enum_old" RENAME TO "report_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."report_type_enum_old" AS ENUM('APPLICATIONS', 'INTERVIEWS', 'HIRES', 'CANDIDATE_ANALYTICS', 'JOB_PERFORMANCE', 'COMPANY_OVERVIEW')`);
        await queryRunner.query(`ALTER TABLE "report" ALTER COLUMN "type" TYPE "public"."report_type_enum_old" USING "type"::"text"::"public"."report_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."report_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."report_type_enum_old" RENAME TO "report_type_enum"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "report" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report" DROP CONSTRAINT "PK_99e4d0bea58cba73c57f935a546"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "report" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "report" ADD CONSTRAINT "PK_99e4d0bea58cba73c57f935a546" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "report" ADD CONSTRAINT "FK_e347c56b008c2057c9887e230aa" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" DROP COLUMN "userAgent"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ADD "userAgent" text`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" DROP COLUMN "ipAddress"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ADD "ipAddress" character varying`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ADD "userId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" DROP COLUMN "details"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ADD "details" text`);
        await queryRunner.query(`CREATE TYPE "public"."report_audit_log_action_enum_old" AS ENUM('CREATED', 'UPDATED', 'DELETED', 'VIEWED', 'SHARED', 'DOWNLOADED', 'EXPORTED')`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ALTER COLUMN "action" TYPE "public"."report_audit_log_action_enum_old" USING "action"::"text"::"public"."report_audit_log_action_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."report_audit_log_action_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."report_audit_log_action_enum_old" RENAME TO "report_audit_log_action_enum"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" DROP COLUMN "reportId"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ADD "reportId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" DROP CONSTRAINT "PK_e8cebe2d7eb2190ee1b5cacd21b"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ADD CONSTRAINT "PK_e8cebe2d7eb2190ee1b5cacd21b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ADD CONSTRAINT "FK_72b16ce84a8b798badf608ff948" FOREIGN KEY ("reportId") REFERENCES "report"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP COLUMN "reportId"`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD "reportId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP CONSTRAINT "PK_818f8c1397a8942a9cccf32a3d4"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD CONSTRAINT "PK_818f8c1397a8942a9cccf32a3d4" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD CONSTRAINT "FK_2f82afddd021b3b81482f10639d" FOREIGN KEY ("reportId") REFERENCES "report"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP CONSTRAINT "PK_c7488f713986a70052eb10f1178"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD CONSTRAINT "PK_c7488f713986a70052eb10f1178" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "report_metrics" DROP COLUMN "reportId"`);
        await queryRunner.query(`ALTER TABLE "report_metrics" ADD "reportId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_metrics" DROP CONSTRAINT "PK_8cfe3e42ad3515d6e0b25764f64"`);
        await queryRunner.query(`ALTER TABLE "report_metrics" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "report_metrics" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "report_metrics" ADD CONSTRAINT "PK_8cfe3e42ad3515d6e0b25764f64" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "report_metrics" ADD CONSTRAINT "FK_c44ef0cc4691706c776f3747818" FOREIGN KEY ("reportId") REFERENCES "report"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_template" ALTER COLUMN "config" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."report_template_type_enum_old" AS ENUM('APPLICATIONS', 'INTERVIEWS', 'HIRES', 'CANDIDATE_ANALYTICS', 'JOB_PERFORMANCE', 'COMPANY_OVERVIEW')`);
        await queryRunner.query(`ALTER TABLE "report_template" ALTER COLUMN "type" TYPE "public"."report_template_type_enum_old" USING "type"::"text"::"public"."report_template_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."report_template_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."report_template_type_enum_old" RENAME TO "report_template_type_enum"`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP CONSTRAINT "PK_d2952f5126d6e487e73ec6ae6a3"`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD CONSTRAINT "PK_d2952f5126d6e487e73ec6ae6a3" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" DROP CONSTRAINT "UQ_dec6236278002920979985aba8b"`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" DROP CONSTRAINT "PK_5db8ccc7afe73509bf9bf3e6bf2"`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" ADD CONSTRAINT "PK_5db8ccc7afe73509bf9bf3e6bf2" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "security_log" DROP COLUMN "details"`);
        await queryRunner.query(`ALTER TABLE "security_log" ADD "details" text`);
        await queryRunner.query(`ALTER TABLE "security_log" DROP CONSTRAINT "PK_efed13f4d5863b4dd080994b486"`);
        await queryRunner.query(`ALTER TABLE "security_log" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "security_log" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "security_log" ADD CONSTRAINT "PK_efed13f4d5863b4dd080994b486" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "application" DROP COLUMN "acceptedAt"`);
        await queryRunner.query(`ALTER TABLE "application" DROP COLUMN "rejectedAt"`);
        await queryRunner.query(`ALTER TABLE "application" DROP COLUMN "interviewedAt"`);
        await queryRunner.query(`ALTER TABLE "application" DROP COLUMN "interviewScheduledAt"`);
        await queryRunner.query(`ALTER TABLE "application" DROP COLUMN "reviewedAt"`);
        await queryRunner.query(`ALTER TABLE "application" DROP COLUMN "companyNotes"`);
        await queryRunner.query(`ALTER TABLE "application" DROP COLUMN "recommendationsGeneratedAt"`);
        await queryRunner.query(`ALTER TABLE "application" DROP COLUMN "aiSecondInterviewRecommendations"`);
        await queryRunner.query(`ALTER TABLE "application" DROP COLUMN "aiInterviewRecommendations"`);
        await queryRunner.query(`ALTER TABLE "application" DROP COLUMN "aiCvRecommendations"`);
        await queryRunner.query(`ALTER TABLE "application" DROP COLUMN "analyzedAt"`);
        await queryRunner.query(`ALTER TABLE "application" DROP COLUMN "cvAnalysisResults"`);
        await queryRunner.query(`ALTER TABLE "application" DROP COLUMN "cvAnalysisScore"`);
        await queryRunner.query(`ALTER TABLE "application" DROP COLUMN "noticePeriod"`);
        await queryRunner.query(`ALTER TABLE "application" DROP COLUMN "expectedSalary"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN "read"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN "category"`);
        await queryRunner.query(`DROP TYPE "public"."notification_category_enum"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "checksum"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "version"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "tags"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "archivedAt"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "isArchived"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "isPublic"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "autoDelete"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "recordCount"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "executionTime"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "generatedBy"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "templateId"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "fileMimeType"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "fileSize"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "fileName"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "fileUrl"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "timeoutAt"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "maxExecutionTime"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "executionStatus"`);
        await queryRunner.query(`DROP TYPE "public"."report_executionstatus_enum"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "parameters"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "filters"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "dataSource"`);
        await queryRunner.query(`DROP TYPE "public"."report_datasource_enum"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "query"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "priority"`);
        await queryRunner.query(`DROP TYPE "public"."report_priority_enum"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "scope"`);
        await queryRunner.query(`DROP TYPE "public"."report_scope_enum"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "format"`);
        await queryRunner.query(`DROP TYPE "public"."report_format_enum"`);
        await queryRunner.query(`ALTER TABLE "report" DROP COLUMN "category"`);
        await queryRunner.query(`DROP TYPE "public"."report_category_enum"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" DROP COLUMN "riskLevel"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" DROP COLUMN "newValues"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" DROP COLUMN "oldValues"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" DROP COLUMN "duration"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" DROP COLUMN "requestId"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" DROP COLUMN "sessionId"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" DROP COLUMN "success"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP COLUMN "shareNote"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP COLUMN "sharedBy"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP COLUMN "watermark"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP COLUMN "allowDownload"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP COLUMN "requireLogin"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP COLUMN "isPublic"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP COLUMN "ipRestrictions"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP COLUMN "lastAccessed"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP COLUMN "maxAccessCount"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP COLUMN "accessCount"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP COLUMN "revokedAt"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP COLUMN "isRevoked"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP CONSTRAINT "UQ_65a42b8d298382583c51c2b3958"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP COLUMN "accessToken"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP COLUMN "permission"`);
        await queryRunner.query(`DROP TYPE "public"."report_share_permission_enum"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP COLUMN "sharedWith"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "lastSuccessfulRun"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "lastError"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "consecutiveFailures"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "maxRetries"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "retryCount"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "maxExecutionTime"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "includeAttachment"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "emailBody"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "emailSubject"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "deliveryFormat"`);
        await queryRunner.query(`DROP TYPE "public"."report_schedule_deliveryformat_enum"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "recipients"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "timezone"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "isPaused"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "lastRun"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "nextRun"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "endDate"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "startDate"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "cronExpression"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "frequency"`);
        await queryRunner.query(`DROP TYPE "public"."report_schedule_frequency_enum"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP CONSTRAINT "UQ_675bc246be79896c578a1945fea"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP COLUMN "reportId"`);
        await queryRunner.query(`ALTER TABLE "report_metrics" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "report_metrics" DROP COLUMN "dimension"`);
        await queryRunner.query(`ALTER TABLE "report_metrics" DROP COLUMN "metricType"`);
        await queryRunner.query(`DROP TYPE "public"."report_metrics_metrictype_enum"`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP COLUMN "lastUsed"`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP COLUMN "usageCount"`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP COLUMN "isSystem"`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP COLUMN "version"`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP COLUMN "validationError"`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP COLUMN "validatedAt"`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP COLUMN "isValidated"`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP COLUMN "defaultParameters"`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP COLUMN "defaultFilters"`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP COLUMN "queryTemplate"`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP COLUMN "dataSource"`);
        await queryRunner.query(`DROP TYPE "public"."report_template_datasource_enum"`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP COLUMN "scope"`);
        await queryRunner.query(`DROP TYPE "public"."report_template_scope_enum"`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP COLUMN "format"`);
        await queryRunner.query(`DROP TYPE "public"."report_template_format_enum"`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP COLUMN "category"`);
        await queryRunner.query(`DROP TYPE "public"."report_template_category_enum"`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "security_log" DROP COLUMN "severity"`);
        await queryRunner.query(`ALTER TABLE "security_log" DROP COLUMN "userAgentHash"`);
        await queryRunner.query(`ALTER TABLE "security_log" DROP COLUMN "ipHash"`);
        await queryRunner.query(`ALTER TABLE "security_log" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "notification" ADD "isRead" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD "sharedById" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD "sharedWithId" character varying NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."report_share_permissions_enum" AS ENUM('VIEW', 'EDIT', 'ADMIN')`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD "permissions" "public"."report_share_permissions_enum" NOT NULL DEFAULT 'VIEW'`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "userId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "nextRunAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "lastRunAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "scheduleConfig" json NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."report_schedule_scheduletype_enum" AS ENUM('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY')`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "scheduleType" "public"."report_schedule_scheduletype_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "companyId" uuid`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD "templateId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_metrics" ADD "metricUnit" character varying`);
        await queryRunner.query(`ALTER TABLE "report_metrics" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD "userId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" ADD "createdById" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" ADD "participants" text array NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" ADD "roomId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" ADD CONSTRAINT "UQ_f02412c2f98aa1927bbf1a6c0cd" UNIQUE ("roomId")`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" ADD "maxParticipants" integer NOT NULL DEFAULT '2'`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" ADD "interviewId" uuid`);
        await queryRunner.query(`ALTER TABLE "security_log" ADD "userAgent" text`);
        await queryRunner.query(`ALTER TABLE "security_log" ADD "ipAddress" character varying`);
        await queryRunner.query(`ALTER TABLE "security_log" ADD "resourceId" character varying`);
        await queryRunner.query(`ALTER TABLE "security_log" ADD "resource" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "security_log" ADD "success" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`CREATE TYPE "public"."security_log_action_enum" AS ENUM('LOGIN', 'LOGOUT', 'PASSWORD_CHANGE', 'PROFILE_UPDATE', 'PERMISSION_CHANGE', 'DATA_ACCESS', 'DATA_MODIFICATION', 'SECURITY_BREACH')`);
        await queryRunner.query(`ALTER TABLE "security_log" ADD "action" "public"."security_log_action_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ADD CONSTRAINT "FK_f5383a793f34f331400df11f2f8" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD CONSTRAINT "FK_673d6ee83e9f5bc6d60f9df909a" FOREIGN KEY ("sharedWithId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD CONSTRAINT "FK_2fb547bb43affa1dca2bcd4d339" FOREIGN KEY ("sharedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD CONSTRAINT "FK_0ecd8c8f8baedd7289628818744" FOREIGN KEY ("templateId") REFERENCES "report_template"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD CONSTRAINT "FK_cce538277486b0782d385414b92" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD CONSTRAINT "FK_1322e1ea1a925f933c0dd29de91" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD CONSTRAINT "FK_28b94f42bd2fc619e33d397c059" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" ADD CONSTRAINT "FK_1f1efdcae59ea4b800cef779683" FOREIGN KEY ("interviewId") REFERENCES "interview"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" ADD CONSTRAINT "FK_10b8c1b5a5312ff18748f12bb2a" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "security_log" ADD CONSTRAINT "FK_1de635e6dd079e75eb11db8303c" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
