import { MigrationInterface, QueryRunner } from "typeorm";

export class AddAllEntities1760490853004 implements MigrationInterface {
    name = 'AddAllEntities1760490853004'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_3b57d5a6b0b7e3e4c3b3b3b3b3b"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_1ced25315b8ef6d898de3a0cffe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e12875dfb3b1d92d7d7c5377e2"`);
        await queryRunner.query(`CREATE TABLE "address" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "street" character varying, "city" character varying, "state" character varying, "country" character varying, "zipCode" character varying, "latitude" double precision, "longitude" double precision, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d92de1f82754668b5f5f5dd4fd5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."company_size_enum" AS ENUM('SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE')`);
        await queryRunner.query(`CREATE TABLE "company" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "website" character varying, "logo" character varying, "industry" character varying, "size" "public"."company_size_enum", "founded" date, "location" character varying, "addressId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_3737905699894299444476dd79" UNIQUE ("addressId"), CONSTRAINT "PK_056f7854a7afdba7cbd6d45fc20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "api_key" ("id" character varying NOT NULL, "key" character varying NOT NULL, "name" character varying, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "expiresAt" TIMESTAMP, "userId" character varying NOT NULL, CONSTRAINT "UQ_fb080786c16de6ace7ed0b69f7d" UNIQUE ("key"), CONSTRAINT "PK_b1bd840641b8acbaad89c3d8d11" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."security_log_action_enum" AS ENUM('LOGIN', 'LOGOUT', 'PASSWORD_CHANGE', 'PROFILE_UPDATE', 'PERMISSION_CHANGE', 'DATA_ACCESS', 'DATA_MODIFICATION', 'SECURITY_BREACH')`);
        await queryRunner.query(`CREATE TABLE "security_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying, "action" "public"."security_log_action_enum" NOT NULL, "resource" character varying NOT NULL, "resourceId" character varying, "details" text, "ipAddress" character varying, "userAgent" text, "success" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_efed13f4d5863b4dd080994b486" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "application_note" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "applicationId" uuid NOT NULL, "userId" character varying NOT NULL, "note" text NOT NULL, "isPrivate" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7f566bcb8dbe1afd09c325b23fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."application_status_enum" AS ENUM('PENDING', 'REVIEWED', 'SHORTLISTED', 'INTERVIEWED', 'OFFERED', 'HIRED', 'REJECTED', 'WITHDRAWN')`);
        await queryRunner.query(`CREATE TABLE "application" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "jobId" character varying NOT NULL, "candidateId" character varying NOT NULL, "status" "public"."application_status_enum" NOT NULL DEFAULT 'PENDING', "appliedAt" TIMESTAMP NOT NULL DEFAULT now(), "coverLetter" text, "resumeUrl" character varying, "source" character varying, "notes" text, "aiAnalysis" json, "interviewScheduled" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_569e0c3e863ebdf5f2408ee1670" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "transcript" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "interviewId" uuid NOT NULL, "content" text NOT NULL, "speaker" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "confidence" double precision, "language" character varying NOT NULL DEFAULT 'english', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b5b7a9bdb53103727ced1eec10e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."interview_type_enum" AS ENUM('VIDEO', 'PHONE', 'IN_PERSON')`);
        await queryRunner.query(`CREATE TYPE "public"."interview_status_enum" AS ENUM('SCHEDULED', 'COMPLETED', 'CANCELLED', 'NO_SHOW')`);
        await queryRunner.query(`CREATE TABLE "interview" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "applicationId" uuid NOT NULL, "interviewerId" character varying NOT NULL, "scheduledAt" TIMESTAMP NOT NULL, "duration" integer, "type" "public"."interview_type_enum" NOT NULL DEFAULT 'VIDEO', "status" "public"."interview_status_enum" NOT NULL DEFAULT 'SCHEDULED', "notes" text, "feedback" text, "rating" integer, "aiAnalysis" json, "recordingUrl" character varying, "roomId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_44c49a4feadefa5c6fa78bfb7d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "live_kit_room" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "roomId" character varying NOT NULL, "name" character varying NOT NULL, "interviewId" uuid, "participants" text array NOT NULL DEFAULT '{}', "isActive" boolean NOT NULL DEFAULT true, "maxParticipants" integer NOT NULL DEFAULT '2', "createdById" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f02412c2f98aa1927bbf1a6c0cd" UNIQUE ("roomId"), CONSTRAINT "PK_5db8ccc7afe73509bf9bf3e6bf2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "report_metrics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reportId" uuid NOT NULL, "metricName" character varying NOT NULL, "metricValue" double precision NOT NULL, "metricUnit" character varying, "period" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8cfe3e42ad3515d6e0b25764f64" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."report_share_permissions_enum" AS ENUM('VIEW', 'EDIT', 'ADMIN')`);
        await queryRunner.query(`CREATE TABLE "report_share" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reportId" uuid NOT NULL, "sharedWithId" character varying NOT NULL, "sharedById" character varying NOT NULL, "permissions" "public"."report_share_permissions_enum" NOT NULL DEFAULT 'VIEW', "expiresAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_818f8c1397a8942a9cccf32a3d4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."report_audit_log_action_enum" AS ENUM('CREATED', 'UPDATED', 'DELETED', 'VIEWED', 'SHARED', 'DOWNLOADED', 'EXPORTED')`);
        await queryRunner.query(`CREATE TABLE "report_audit_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reportId" uuid NOT NULL, "userId" character varying NOT NULL, "action" "public"."report_audit_log_action_enum" NOT NULL, "details" text, "ipAddress" character varying, "userAgent" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e8cebe2d7eb2190ee1b5cacd21b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."report_type_enum" AS ENUM('APPLICATIONS', 'INTERVIEWS', 'HIRES', 'CANDIDATE_ANALYTICS', 'JOB_PERFORMANCE', 'COMPANY_OVERVIEW')`);
        await queryRunner.query(`CREATE TYPE "public"."report_status_enum" AS ENUM('PENDING', 'GENERATING', 'COMPLETED', 'FAILED', 'EXPIRED')`);
        await queryRunner.query(`CREATE TABLE "report" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "type" "public"."report_type_enum" NOT NULL, "userId" character varying NOT NULL, "companyId" uuid, "config" json NOT NULL, "data" json, "generatedAt" TIMESTAMP, "expiresAt" TIMESTAMP, "status" "public"."report_status_enum" NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_99e4d0bea58cba73c57f935a546" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."report_schedule_scheduletype_enum" AS ENUM('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY')`);
        await queryRunner.query(`CREATE TABLE "report_schedule" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "templateId" uuid NOT NULL, "userId" character varying NOT NULL, "companyId" uuid, "scheduleType" "public"."report_schedule_scheduletype_enum" NOT NULL, "scheduleConfig" json NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "lastRunAt" TIMESTAMP, "nextRunAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c7488f713986a70052eb10f1178" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."report_template_type_enum" AS ENUM('APPLICATIONS', 'INTERVIEWS', 'HIRES', 'CANDIDATE_ANALYTICS', 'JOB_PERFORMANCE', 'COMPANY_OVERVIEW')`);
        await queryRunner.query(`CREATE TABLE "report_template" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "type" "public"."report_template_type_enum" NOT NULL, "userId" character varying NOT NULL, "companyId" uuid, "config" json NOT NULL, "isPublic" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d2952f5126d6e487e73ec6ae6a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."invitation_usertype_enum" AS ENUM('SYSTEM', 'COMPANY', 'CANDIDATE', 'ADMIN')`);
        await queryRunner.query(`CREATE TYPE "public"."invitation_status_enum" AS ENUM('PENDING', 'ACCEPTED', 'EXPIRED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "invitation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "userType" "public"."invitation_usertype_enum" NOT NULL, "status" "public"."invitation_status_enum" NOT NULL DEFAULT 'PENDING', "invitedById" character varying NOT NULL, "companyId" uuid, "expiresAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_beb994737756c0f18a1c1f8669c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."communication_type_enum" AS ENUM('EMAIL', 'SMS', 'WHATSAPP', 'IN_APP')`);
        await queryRunner.query(`CREATE TABLE "communication" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "applicationId" uuid NOT NULL, "senderId" character varying NOT NULL, "recipientId" character varying NOT NULL, "type" "public"."communication_type_enum" NOT NULL, "subject" character varying, "message" text NOT NULL, "isRead" boolean NOT NULL DEFAULT false, "sentAt" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_392407b9e9100bee1a64e26cd5d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."whats_app_message_status_enum" AS ENUM('SENT', 'DELIVERED', 'READ', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "whats_app_message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "communicationId" uuid NOT NULL, "messageId" character varying, "status" "public"."whats_app_message_status_enum" NOT NULL DEFAULT 'SENT', "deliveredAt" TIMESTAMP, "readAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c5220a47bc7878e72cb4e313421" UNIQUE ("communicationId"), CONSTRAINT "REL_c5220a47bc7878e72cb4e31342" UNIQUE ("communicationId"), CONSTRAINT "PK_35fcd9935d7d77dcf686b6290a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "education" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "candidateProfileId" uuid NOT NULL, "institution" character varying NOT NULL, "degree" character varying NOT NULL, "fieldOfStudy" character varying, "startDate" date, "endDate" date, "grade" character varying, "description" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bf3d38701b3030a8ad634d43bd6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cv" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "candidateProfileId" uuid NOT NULL, "fileName" character varying NOT NULL, "fileUrl" character varying NOT NULL, "fileSize" integer, "mimeType" character varying, "isPrimary" boolean NOT NULL DEFAULT false, "uploadedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4ddf7891daf83c3506efa503bb8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."candidate_profile_availability_enum" AS ENUM('AVAILABLE', 'NOT_AVAILABLE', 'LOOKING')`);
        await queryRunner.query(`CREATE TYPE "public"."candidate_profile_preferredworktype_enum" AS ENUM('ONSITE', 'REMOTE', 'HYBRID')`);
        await queryRunner.query(`CREATE TABLE "candidate_profile" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "firstName" character varying, "lastName" character varying, "phone" character varying, "location" character varying, "bio" text, "skills" text array NOT NULL DEFAULT '{}', "experience" character varying, "education" character varying, "linkedinUrl" character varying, "githubUrl" character varying, "portfolioUrl" character varying, "resumeUrl" character varying, "availability" "public"."candidate_profile_availability_enum", "salaryExpectation" character varying, "preferredWorkType" "public"."candidate_profile_preferredworktype_enum", "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ab092d6b881f23c10ff1b801829" UNIQUE ("userId"), CONSTRAINT "REL_ab092d6b881f23c10ff1b80182" UNIQUE ("userId"), CONSTRAINT "PK_404029cefcd04a9d68f13f9d8e3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "work_experience" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "candidateProfileId" uuid NOT NULL, "company" character varying NOT NULL, "position" character varying NOT NULL, "startDate" date NOT NULL, "endDate" date, "description" text, "isCurrent" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d4bef63ad6da7ec327515c121bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "job" DROP COLUMN "company"`);
        await queryRunner.query(`ALTER TABLE "job" ADD "companyId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "job" ALTER COLUMN "department" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "job" ALTER COLUMN "salary" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "job" DROP COLUMN "type"`);
        await queryRunner.query(`CREATE TYPE "public"."job_type_enum" AS ENUM('FULL_TIME', 'PART_TIME', 'CONTRACT', 'REMOTE')`);
        await queryRunner.query(`ALTER TABLE "job" ADD "type" "public"."job_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "job" ALTER COLUMN "deadline" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "job" ALTER COLUMN "shortDescription" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "job" ALTER COLUMN "responsibilities" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "job" ALTER COLUMN "requirements" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "job" ALTER COLUMN "benefits" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "job" DROP COLUMN "skills"`);
        await queryRunner.query(`ALTER TABLE "job" ADD "skills" text array NOT NULL`);
        await queryRunner.query(`ALTER TABLE "job" ALTER COLUMN "experience" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "job" ALTER COLUMN "education" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "job" DROP COLUMN "jobLevel"`);
        await queryRunner.query(`CREATE TYPE "public"."job_joblevel_enum" AS ENUM('ENTRY', 'MID', 'SENIOR', 'EXECUTIVE')`);
        await queryRunner.query(`ALTER TABLE "job" ADD "jobLevel" "public"."job_joblevel_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "job" DROP COLUMN "workType"`);
        await queryRunner.query(`CREATE TYPE "public"."job_worktype_enum" AS ENUM('ONSITE', 'REMOTE', 'HYBRID')`);
        await queryRunner.query(`ALTER TABLE "job" ADD "workType" "public"."job_worktype_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "job" ALTER COLUMN "industry" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "job" ALTER COLUMN "companyDescription" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "job" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."job_status_enum" AS ENUM('DRAFT', 'ACTIVE', 'PAUSED', 'CLOSED', 'EXPIRED', 'DELETED')`);
        await queryRunner.query(`ALTER TABLE "job" ADD "status" "public"."job_status_enum" NOT NULL DEFAULT 'DRAFT'`);
        await queryRunner.query(`ALTER TABLE "job" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "userType"`);
        await queryRunner.query(`CREATE TYPE "public"."user_usertype_enum" AS ENUM('SYSTEM', 'COMPANY', 'CANDIDATE', 'ADMIN')`);
        await queryRunner.query(`ALTER TABLE "user" ADD "userType" "public"."user_usertype_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "companyId" uuid`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_e66170573cabd565dab1132727d" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_49dd92c00fe0d00a40602e2e171" FOREIGN KEY ("postedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company" ADD CONSTRAINT "FK_3737905699894299444476dd79c" FOREIGN KEY ("addressId") REFERENCES "address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_86586021a26d1180b0968f98502" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD CONSTRAINT "FK_277972f4944205eb29127f9bb6c" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "security_log" ADD CONSTRAINT "FK_1de635e6dd079e75eb11db8303c" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_note" ADD CONSTRAINT "FK_546f9c0eff39484764e5fe09290" FOREIGN KEY ("applicationId") REFERENCES "application"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_note" ADD CONSTRAINT "FK_5f195f30a2aa3160d902c186c6b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application" ADD CONSTRAINT "FK_dbc0341504212f830211b69ba0c" FOREIGN KEY ("jobId") REFERENCES "job"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application" ADD CONSTRAINT "FK_56bd5315980a6bcd995a54df8fe" FOREIGN KEY ("candidateId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transcript" ADD CONSTRAINT "FK_2ede2eb745d7ea378687fcb7b35" FOREIGN KEY ("interviewId") REFERENCES "interview"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "interview" ADD CONSTRAINT "FK_35c375805d4e8809adf67f635bb" FOREIGN KEY ("applicationId") REFERENCES "application"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "interview" ADD CONSTRAINT "FK_540ce8c6be84d9286b5cd0de493" FOREIGN KEY ("interviewerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" ADD CONSTRAINT "FK_1f1efdcae59ea4b800cef779683" FOREIGN KEY ("interviewId") REFERENCES "interview"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" ADD CONSTRAINT "FK_10b8c1b5a5312ff18748f12bb2a" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_metrics" ADD CONSTRAINT "FK_c44ef0cc4691706c776f3747818" FOREIGN KEY ("reportId") REFERENCES "report"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD CONSTRAINT "FK_2f82afddd021b3b81482f10639d" FOREIGN KEY ("reportId") REFERENCES "report"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD CONSTRAINT "FK_673d6ee83e9f5bc6d60f9df909a" FOREIGN KEY ("sharedWithId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_share" ADD CONSTRAINT "FK_2fb547bb43affa1dca2bcd4d339" FOREIGN KEY ("sharedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ADD CONSTRAINT "FK_72b16ce84a8b798badf608ff948" FOREIGN KEY ("reportId") REFERENCES "report"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" ADD CONSTRAINT "FK_f5383a793f34f331400df11f2f8" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report" ADD CONSTRAINT "FK_e347c56b008c2057c9887e230aa" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report" ADD CONSTRAINT "FK_5b0c56cb46dbc2e4f7eeea91aeb" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD CONSTRAINT "FK_0ecd8c8f8baedd7289628818744" FOREIGN KEY ("templateId") REFERENCES "report_template"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD CONSTRAINT "FK_cce538277486b0782d385414b92" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_schedule" ADD CONSTRAINT "FK_1322e1ea1a925f933c0dd29de91" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD CONSTRAINT "FK_28b94f42bd2fc619e33d397c059" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_template" ADD CONSTRAINT "FK_287f288d47319d2fc7826f09b1b" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_1ced25315eb974b73391fb1c81b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitation" ADD CONSTRAINT "FK_603764233ba5c97400836665523" FOREIGN KEY ("invitedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitation" ADD CONSTRAINT "FK_757968494b8501e4e3b27860fb0" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "communication" ADD CONSTRAINT "FK_6fdd6bffa041d6a6b4c0184ccbf" FOREIGN KEY ("applicationId") REFERENCES "application"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "communication" ADD CONSTRAINT "FK_b60ec750c6d4edc5299b6f34c26" FOREIGN KEY ("senderId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "communication" ADD CONSTRAINT "FK_46d87ba383d66fe91cf2b47963c" FOREIGN KEY ("recipientId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "whats_app_message" ADD CONSTRAINT "FK_c5220a47bc7878e72cb4e313421" FOREIGN KEY ("communicationId") REFERENCES "communication"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "education" ADD CONSTRAINT "FK_020a2f7db1c68a2d9eb9fe8c09d" FOREIGN KEY ("candidateProfileId") REFERENCES "candidate_profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cv" ADD CONSTRAINT "FK_68b505eded7c9f3add3afe9ff66" FOREIGN KEY ("candidateProfileId") REFERENCES "candidate_profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "candidate_profile" ADD CONSTRAINT "FK_ab092d6b881f23c10ff1b801829" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_experience" ADD CONSTRAINT "FK_fe64019bc2a32b29226442f7342" FOREIGN KEY ("candidateProfileId") REFERENCES "candidate_profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "work_experience" DROP CONSTRAINT "FK_fe64019bc2a32b29226442f7342"`);
        await queryRunner.query(`ALTER TABLE "candidate_profile" DROP CONSTRAINT "FK_ab092d6b881f23c10ff1b801829"`);
        await queryRunner.query(`ALTER TABLE "cv" DROP CONSTRAINT "FK_68b505eded7c9f3add3afe9ff66"`);
        await queryRunner.query(`ALTER TABLE "education" DROP CONSTRAINT "FK_020a2f7db1c68a2d9eb9fe8c09d"`);
        await queryRunner.query(`ALTER TABLE "whats_app_message" DROP CONSTRAINT "FK_c5220a47bc7878e72cb4e313421"`);
        await queryRunner.query(`ALTER TABLE "communication" DROP CONSTRAINT "FK_46d87ba383d66fe91cf2b47963c"`);
        await queryRunner.query(`ALTER TABLE "communication" DROP CONSTRAINT "FK_b60ec750c6d4edc5299b6f34c26"`);
        await queryRunner.query(`ALTER TABLE "communication" DROP CONSTRAINT "FK_6fdd6bffa041d6a6b4c0184ccbf"`);
        await queryRunner.query(`ALTER TABLE "invitation" DROP CONSTRAINT "FK_757968494b8501e4e3b27860fb0"`);
        await queryRunner.query(`ALTER TABLE "invitation" DROP CONSTRAINT "FK_603764233ba5c97400836665523"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_1ced25315eb974b73391fb1c81b"`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP CONSTRAINT "FK_287f288d47319d2fc7826f09b1b"`);
        await queryRunner.query(`ALTER TABLE "report_template" DROP CONSTRAINT "FK_28b94f42bd2fc619e33d397c059"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP CONSTRAINT "FK_1322e1ea1a925f933c0dd29de91"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP CONSTRAINT "FK_cce538277486b0782d385414b92"`);
        await queryRunner.query(`ALTER TABLE "report_schedule" DROP CONSTRAINT "FK_0ecd8c8f8baedd7289628818744"`);
        await queryRunner.query(`ALTER TABLE "report" DROP CONSTRAINT "FK_5b0c56cb46dbc2e4f7eeea91aeb"`);
        await queryRunner.query(`ALTER TABLE "report" DROP CONSTRAINT "FK_e347c56b008c2057c9887e230aa"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" DROP CONSTRAINT "FK_f5383a793f34f331400df11f2f8"`);
        await queryRunner.query(`ALTER TABLE "report_audit_log" DROP CONSTRAINT "FK_72b16ce84a8b798badf608ff948"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP CONSTRAINT "FK_2fb547bb43affa1dca2bcd4d339"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP CONSTRAINT "FK_673d6ee83e9f5bc6d60f9df909a"`);
        await queryRunner.query(`ALTER TABLE "report_share" DROP CONSTRAINT "FK_2f82afddd021b3b81482f10639d"`);
        await queryRunner.query(`ALTER TABLE "report_metrics" DROP CONSTRAINT "FK_c44ef0cc4691706c776f3747818"`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" DROP CONSTRAINT "FK_10b8c1b5a5312ff18748f12bb2a"`);
        await queryRunner.query(`ALTER TABLE "live_kit_room" DROP CONSTRAINT "FK_1f1efdcae59ea4b800cef779683"`);
        await queryRunner.query(`ALTER TABLE "interview" DROP CONSTRAINT "FK_540ce8c6be84d9286b5cd0de493"`);
        await queryRunner.query(`ALTER TABLE "interview" DROP CONSTRAINT "FK_35c375805d4e8809adf67f635bb"`);
        await queryRunner.query(`ALTER TABLE "transcript" DROP CONSTRAINT "FK_2ede2eb745d7ea378687fcb7b35"`);
        await queryRunner.query(`ALTER TABLE "application" DROP CONSTRAINT "FK_56bd5315980a6bcd995a54df8fe"`);
        await queryRunner.query(`ALTER TABLE "application" DROP CONSTRAINT "FK_dbc0341504212f830211b69ba0c"`);
        await queryRunner.query(`ALTER TABLE "application_note" DROP CONSTRAINT "FK_5f195f30a2aa3160d902c186c6b"`);
        await queryRunner.query(`ALTER TABLE "application_note" DROP CONSTRAINT "FK_546f9c0eff39484764e5fe09290"`);
        await queryRunner.query(`ALTER TABLE "security_log" DROP CONSTRAINT "FK_1de635e6dd079e75eb11db8303c"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP CONSTRAINT "FK_277972f4944205eb29127f9bb6c"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_86586021a26d1180b0968f98502"`);
        await queryRunner.query(`ALTER TABLE "company" DROP CONSTRAINT "FK_3737905699894299444476dd79c"`);
        await queryRunner.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_49dd92c00fe0d00a40602e2e171"`);
        await queryRunner.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_e66170573cabd565dab1132727d"`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "companyId" character varying`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "userType"`);
        await queryRunner.query(`DROP TYPE "public"."user_usertype_enum"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "userType" character varying NOT NULL DEFAULT 'CANDIDATE'`);
        await queryRunner.query(`ALTER TABLE "job" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "job" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."job_status_enum"`);
        await queryRunner.query(`ALTER TABLE "job" ADD "status" character varying NOT NULL DEFAULT 'DRAFT'`);
        await queryRunner.query(`ALTER TABLE "job" ALTER COLUMN "companyDescription" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "job" ALTER COLUMN "industry" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "job" DROP COLUMN "workType"`);
        await queryRunner.query(`DROP TYPE "public"."job_worktype_enum"`);
        await queryRunner.query(`ALTER TABLE "job" ADD "workType" character varying NOT NULL DEFAULT 'ONSITE'`);
        await queryRunner.query(`ALTER TABLE "job" DROP COLUMN "jobLevel"`);
        await queryRunner.query(`DROP TYPE "public"."job_joblevel_enum"`);
        await queryRunner.query(`ALTER TABLE "job" ADD "jobLevel" character varying NOT NULL DEFAULT 'ENTRY'`);
        await queryRunner.query(`ALTER TABLE "job" ALTER COLUMN "education" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "job" ALTER COLUMN "experience" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "job" DROP COLUMN "skills"`);
        await queryRunner.query(`ALTER TABLE "job" ADD "skills" text NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "job" ALTER COLUMN "benefits" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "job" ALTER COLUMN "requirements" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "job" ALTER COLUMN "responsibilities" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "job" ALTER COLUMN "shortDescription" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "job" ALTER COLUMN "deadline" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "job" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."job_type_enum"`);
        await queryRunner.query(`ALTER TABLE "job" ADD "type" character varying NOT NULL DEFAULT 'FULL_TIME'`);
        await queryRunner.query(`ALTER TABLE "job" ALTER COLUMN "salary" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "job" ALTER COLUMN "department" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "job" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "job" ADD "company" character varying NOT NULL`);
        await queryRunner.query(`DROP TABLE "work_experience"`);
        await queryRunner.query(`DROP TABLE "candidate_profile"`);
        await queryRunner.query(`DROP TYPE "public"."candidate_profile_preferredworktype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."candidate_profile_availability_enum"`);
        await queryRunner.query(`DROP TABLE "cv"`);
        await queryRunner.query(`DROP TABLE "education"`);
        await queryRunner.query(`DROP TABLE "whats_app_message"`);
        await queryRunner.query(`DROP TYPE "public"."whats_app_message_status_enum"`);
        await queryRunner.query(`DROP TABLE "communication"`);
        await queryRunner.query(`DROP TYPE "public"."communication_type_enum"`);
        await queryRunner.query(`DROP TABLE "invitation"`);
        await queryRunner.query(`DROP TYPE "public"."invitation_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."invitation_usertype_enum"`);
        await queryRunner.query(`DROP TABLE "report_template"`);
        await queryRunner.query(`DROP TYPE "public"."report_template_type_enum"`);
        await queryRunner.query(`DROP TABLE "report_schedule"`);
        await queryRunner.query(`DROP TYPE "public"."report_schedule_scheduletype_enum"`);
        await queryRunner.query(`DROP TABLE "report"`);
        await queryRunner.query(`DROP TYPE "public"."report_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."report_type_enum"`);
        await queryRunner.query(`DROP TABLE "report_audit_log"`);
        await queryRunner.query(`DROP TYPE "public"."report_audit_log_action_enum"`);
        await queryRunner.query(`DROP TABLE "report_share"`);
        await queryRunner.query(`DROP TYPE "public"."report_share_permissions_enum"`);
        await queryRunner.query(`DROP TABLE "report_metrics"`);
        await queryRunner.query(`DROP TABLE "live_kit_room"`);
        await queryRunner.query(`DROP TABLE "interview"`);
        await queryRunner.query(`DROP TYPE "public"."interview_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."interview_type_enum"`);
        await queryRunner.query(`DROP TABLE "transcript"`);
        await queryRunner.query(`DROP TABLE "application"`);
        await queryRunner.query(`DROP TYPE "public"."application_status_enum"`);
        await queryRunner.query(`DROP TABLE "application_note"`);
        await queryRunner.query(`DROP TABLE "security_log"`);
        await queryRunner.query(`DROP TYPE "public"."security_log_action_enum"`);
        await queryRunner.query(`DROP TABLE "api_key"`);
        await queryRunner.query(`DROP TABLE "company"`);
        await queryRunner.query(`DROP TYPE "public"."company_size_enum"`);
        await queryRunner.query(`DROP TABLE "address"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e12875dfb3b1d92d7d7c5377e2" ON "user" ("email") `);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_1ced25315b8ef6d898de3a0cffe" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_3b57d5a6b0b7e3e4c3b3b3b3b3b" FOREIGN KEY ("postedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
