-- CreateEnum
CREATE TYPE "Industry" AS ENUM ('TECHNOLOGY', 'HEALTHCARE', 'FINANCE', 'EDUCATION', 'MANUFACTURING', 'RETAIL', 'CONSTRUCTION', 'TRANSPORTATION', 'HOSPITALITY', 'CONSULTING', 'MARKETING', 'REAL_ESTATE', 'MEDIA', 'AGRICULTURE', 'ENERGY', 'GOVERNMENT', 'NON_PROFIT', 'OTHER');

-- AlterTable
ALTER TABLE "companies" ADD COLUMN     "industry" "Industry",
ADD COLUMN     "numberOfEmployees" INTEGER;
