version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_HOST=http://host.docker.internal:4005
      - NEXT_PUBLIC_BACKEND_URL=http://host.docker.internal:4005
    restart: unless-stopped
    networks:
      - rolevate-network

networks:
  rolevate-network:
    driver: bridge
